CREATE ALIAS IF NOT EXISTS FT_INIT FOR "org.h2.fulltext.FullText.init";
CALL FT_INIT();
CALL FT_CREATE_INDEX('PUBLIC', 'COMMENTS', NULL);
CALL FT_CREATE_INDEX('PUBLIC', 'CHANNELS', NULL);
--  CALL FTL_DROP_ALL();
