### Get channels paged query
GET {{api-url}}/channels?text=adam&page=0&size=10&sort=videoCount,desc
Accept: application/json

### Delete a channel by Id
DELETE {{api-url}}/channels/UCksTNgiRyQGwi2ODBie8HdA
Accept: application/json

### Get a channel summary

GET {{api-url}}/channels/UCksTNgiRyQGwi2ODBie8HdA
Accept: application/json

###
